#spring:
#  data.mongodb:
#    host: 172.17.0.2
#    port: 27017

logging:
  level:
    com.martinb: DEBUG
    org.springframework.data: TRACE
    io:
      netty: TRACE
    reactor:
      core: TRACE
      util: TRACE